server/db/db.js
server/db/models/products.js

named DB and created product model.

Products models routes

---

server/api/products.js

api bug fix

---

script/seed.js

Product seed file

---

client/components/navbar.js
client/components/user-home.js

more nav links

---

client/components/Checkout/Checkout.js
client/components/Checkout/constants/server.js
client/components/Checkout/constants/stripe.js
client/components/index.js
client/routes.js
package-lock.json
package.json
server/api/index.js
server/api/payment.js
server/constants/frontend.js
server/constants/server.js
server/constants/stripe.js
server/index.js

Stripe functionality

---

client/components/Cart.js
client/routes.js

Navbar cart items

---

client/components/Checkout/constants/stripe.js
server/constants/stripe.js

Secret edits

---

client/components/Cart.js

Feat: Add removeButton to Cart - Closes:#37

---

script/seed.js
server/db/models/product.js

changed price type on product model to int

changed price data type

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
README.md
client/app.js
client/components/Cart.js
client/components/CartList.js
client/components/Checkout/Checkout.js
client/components/ProductCard.js
client/components/ProductList.js
client/routes.js
client/store/cart.js

changed price datatype to integer, wired up checkout to cart so it will take the price total and run that through stripe.

feat: add checkout functionality

---

server/db/models/index.js
server/db/models/order.js

feat: add hooks

---

client/components/CartList.js
package-lock.json
package.json
public/index.html
semantic.json

Simple addition of
npm install semantic-ui-react

Feat: Added Semantic-UI Closes:#48

---

client/components/CartList.js

Feat: Added Simple Styling to Cart Closes:#57

---

server/api/users.js

feat: add cart update route

---

client/components/index.js
client/components/navbar.js

Added Navbar Styling with semantic UI

Added Navbar Styling

---

client/components/ProductCard.js
server/api/users.js
server/db/models/index.js
server/db/models/order.js

refactored db relationships for cart

basic relational model for carts implemented

---

client/components/Navbar.js

feat: add navbar badge

---

client/components/ProductCard.js
script/seed.js
server/api/users.js
server/auth/index.js
server/db/models/order.js

add button on product card now also syncs cart with database if user is logged in

Cart syncing

---

client/components/Navbar.js

fix: create navlinks for active state Closes#67

---

client/components/Navbar.js
client/routes.js

buttons now properly navigate every click, however styling issues were introduced.

bugfix: navbar button functionality

---

.github/PULL_REQUEST_TEMPLATE.md
server/api/users.spec.js

wrote tests for our GET api/users/id route, tests that the correct user is returned and that they properly eager load that users orders

tests: tests for /api/users/id route

---

client/components/Cart.js
client/components/LandingPage.js
client/components/Navbar.js
client/components/ProductCard.js
client/components/ProductList.js
server/db/db.js

removed unneeded commented out code, removed debug console.logs, added some try-catch error handling to async requests that were missing it

tidying up

---

client/components/ProductCard.js

Feat: Simple Styling for Product Card

---

client/routes.js

cleaned up routes folder and got rid of redundant routes.

fix: adjust route naming

---

client/routes.js
server/api/users.js
server/api/utils.js

Added utility middleware that will check that the api route for specific user information can only be reached if the currently logged in users id matches the routes id.

feat: secured user api routes

---

client/components/HomePage.js

added links to our about us section

about us links
